### ISSUE TITLE
Please add hotkey for all options of reaper update utility.

### ISSUE THREAD

**Issue by vgjh2005** [iliaspoulakis/Reaper-Tools#1]
Hi iliaspoulakis:
I am a blind musician. It is nice to find update utility for reaper. It is a necessary script for reaper users. Can you add hotkey for all options on it? Now, screen reader is not so good on reaper script interface. 
In the other hands, I think you can add exit confirm for script window closing when downloading. Last, if download progress is displayed, I think it is a good idea!
Thanks for your hard work!
best wishes!

**Comment by iliaspoulakis** [comment]
Hi vgjh2005,

I'll add some simple hotkeys for the most important features in the next update. A download progress bar would be quite hard to add, but maybe it makes sense to add an exit confirm dialog. I'll look into it.

**Comment by vgjh2005** [comment]
OK. Thanks!

**Comment by iliaspoulakis** [comment]
So I added the following hotkeys:
m: Install latest main version
d: Install latest dev version
M: Open main version changelog in browser
D: Open dev version changelog in browser

If you would prefer different ones, tell me and I'll change them.

**Comment by mespotine** [comment]
@vgjh2005 
Do you use Osara for text to speech in Reaper? If yes, adding text to speech would be possible via scripting.
Here is a Reaper-thread about Osara:
https://forum.cockos.com/showthread.php?t=242284

**Comment by vgjh2005** [comment]
@iliaspoulakis Good works! Thanks!
@mespotine Good idea! Thanks!
