### ISSUE TITLE
Update utility can't get any update info with reaper 6.16 rc8.

### ISSUE THREAD

**Issue by vgjh2005** [iliaspoulakis/Reaper-Tools#2]
Hi
I find the update utility tool can't get any update info in the reaper 6.16 rc8 version.
First, I am using reaper 6.15 to update reaper 6.16 rc8 with update utility. Secondary, I run the script directly and the dialog show me checking update. Finally, the follow info is shown: Could not parse download link!
OS: Win64
Arch: win64
I reinstall reaper 6.15 by using installation. The same internet environment is not changed and the function is normal. I can see the current version and the newest version. If I press download, the downloading dialog will be shown.
I actually don't know why not! Thanks!

**Comment by vgjh2005** [comment]
I am sorry for not to tell you: I am using portable reaper.

**Comment by iliaspoulakis** [comment]
Version 6.16 rc8 introduced version naming changes in the reaper API.  It should now work again with the latest update.

**Comment by vgjh2005** [comment]
Thanks for your good works!
